### ISSUE TITLE
url.indexOf is not a function

### ISSUE THREAD

**Issue by SanthoshRaju91** [ajainvivek/ember-foundation-sass#1]
Hi Ajain,

Hope you are doing good. Working on the same ember project and I found this addon being used for packaging sass with foundation version 5.5.3.

Now this seems to be a issue, since the foundation v5.5.3 is jQuery 3> onwards and we are getting titled error.

You can find the thread [here](https://github.com/zurb/foundation-sites/issues/8834)

I can help you with this by forking the repo, fixing the issue and raising a PR. Would you please take some time in validating and merging the PR.

Warm Regards

**Comment by ajainvivek** [comment]
I am happy to merge the PR. Go ahead and raise a request.

**Comment by SanthoshRaju91** [comment]
Thank you @ajainvivek , I have raised the PR to included foundation-sites instead of zurb's bower/foundation. 

I took a while to test the changes as I needed to publish them to my npm registry and check for changes.

Please validate the changes and merge the PR at your convenience. 

Thought of upgrading the ember-cli version as well, but since the addon acts as bundler to package the foundation sass & js files I did not go with it. Let me know your thoughts as well. Happy to do that as well.

**Comment by ajainvivek** [comment]
I have merged your changes and published. I have added you as a collaborator on the project. I am happy for you to make changes.

**Comment by SanthoshRaju91** [comment]
Thank you
